import type { Metadata } from "next";
import "./globals.css";
import { dmSans } from "@/assets/fonts";
import VanishingButton from "@/components/client/VanishingButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased bg-[#fef1e4] relative min-h-[100vh]`}
      >
        {children}
        <VanishingButton />
      </body>
    </html>
  );
}
